/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.util.ArrayList;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import proyectofinal.Atributos;


/**
 *
 * @author Ramon
 */
public class ventanaDatos extends javax.swing.JInternalFrame {

    private DefaultTableModel modeloTabla = new DefaultTableModel();
    
    /**
     * Creates new form ventanaDatos
     
     */
    ArrayList<String> atributos;
    
    public ventanaDatos(String key,ArrayList<String> atributos,String tipoEntidad) {
        //primero se crea el modelo de la tabla
        agregarModeloTabla();
        //se añaden los renglones
        addRows(atributos);
        initComponents();
        //despues de la finalizacion de la creacion se agrega lo siguiente
        modificarEntidad(key,tipoEntidad);
        
        //agregamos el comboBox
        addComboBox(1, jTable1);
        //agregamos las checkBox
        addCheckBox(4,this.jTable1);
        addCheckBox(5,this.jTable1);
    }
    
    private void modificarEntidad(String key,String tipoEntidad){
        
        
        if (tipoEntidad.equals("entidad")) {//entidad fuerte
            etiquetaEntidad.setText("Entidad: "+key);
        } else{//entidad debil
            etiquetaEntidad.setText("Entidad debil: "+key);
        }
        
    }
    
    private void agregarModeloTabla(){
        //agregamos los nombres de las columnas a la tabla
        modeloTabla.addColumn("Name");
        modeloTabla.addColumn("Datatype");
        modeloTabla.addColumn("Length");
        modeloTabla.addColumn("Precision");
        modeloTabla.addColumn("Not NULL?");
        modeloTabla.addColumn("Primary Key?");
    }
    
    private void addRows(ArrayList<String> atributos){
        
        //recorremos los atributos
        for (String atributo : atributos) {
            //si es una llave primaria
            if (atributo.endsWith("**")) {
                String[] datos = {atributo};
                //,null,null,null,null,null
                modeloTabla.addRow(datos);
            }else{
                String[] datos = {atributo};
                //,null,null,null,null,null
                modeloTabla.addRow(datos);
            }
        }
    }
    
    //metodo para añadir las casillas de seleccion
    private void addCheckBox(int column,JTable table){
        TableColumn td = table.getColumnModel().getColumn(column);
        
        td.setCellEditor(table.getDefaultEditor(Boolean.class));
        td.setCellRenderer(table.getDefaultRenderer(Boolean.class));
    }
    
    public boolean IsSelected(int row,int column,JTable table){
        //regresamos si esta seleccionado
        return table.getValueAt(row, column)!=null;
    }

    private void addComboBox(int column, JTable table){
        //obtenemos la columna de la tabla
        TableColumn td = table.getColumnModel().getColumn(column);
        
        //creamos el comboBox
        JComboBox comboBox = new JComboBox();
        comboBox.addItem("INT");
        comboBox.addItem("VARCHAR");
        comboBox.addItem("FLOAT");
        
        
        //añadimos el combo box a la tabla
        td.setCellEditor(new DefaultCellEditor(comboBox));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        etiquetaEntidad = new javax.swing.JLabel();
        botonGuardar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(modeloTabla);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 560, 299));

        etiquetaEntidad.setText("Entidad");
        jPanel1.add(etiquetaEntidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 240, 20));

        botonGuardar.setText("Crear codigo SQL");
        botonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGuardarActionPerformed(evt);
            }
        });
        jPanel1.add(botonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 0, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 30, 290, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        //recorremos la tabla en busca de la llave primaria
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (IsSelected(i, 5, jTable1)) {
                //se guardara como elemento primario
            }
        }
        
        //recorremos la tabla en busca del elemento not null
        for (int i = 0; i < jTable1.getRowCount(); i++) {
            if (IsSelected(i, 4, jTable1)) {
                
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGuardar;
    private javax.swing.JLabel etiquetaEntidad;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
